### ISSUE TITLE
Arduino Library Manager missing versions

### ISSUE THREAD

**Issue by tobozo** [chrisjoyce911/esp32FOTA#93]
Just found out the Arduino Library Manager has been ignoring all versions of this library since 0.1.4 **because it contains symbolic links in the /test folder**.

poke @per1234 if you're working on a notification system for such situations, this one started two years ago :-)

I'll fix this in 0.2.1 by having the CI to copy the files instead of using the symlinks, but it's unlikely 0.1.6 and 0.2.0 will ever appear in the Arduino Library Manager.

![image](https://user-images.githubusercontent.com/1893754/190620455-d78a628f-d669-4eee-894c-bf80de0afcd8.png)

![image](https://user-images.githubusercontent.com/1893754/190620655-8ac182fd-2411-410f-afa3-d9936935a86c.png)

Platformio registry isn't affected though.

**Comment by per1234** [comment]
Hi @tobozo. I think it might be challenging to set up a notification system for a couple of reasons:

- Some tags might have been created for reasons other than Library Manager publishing (e.g., beta testing, tagging revisions in unrelated branches)
- Anyone is permitted to submit libraries, so who do we notify? The library repository owner, who might have no interest in Library Manager? Or the submitter, who might not have any way to resolve the problem?

Arduino has provided an alternative solution, which is actually far superior in most ways. This is the `arduino/arduino-lint-action` GitHub Actions action. Just add a simple workflow to your repository and the action will run on every push or pull request that changes relevant files in the repository.

Arduino is using this action in all the official library, sketch, and boards platform repositories. Here is an example:

https://github.com/arduino-libraries/Arduino_PF1550/blob/master/.github/workflows/check-arduino.yml

The reason this approach is superior is because the time to catch the problem is before it is introduced into the production branch of the repository. A universal notification system as you propose could only notify of problems after they have already been released.

**Comment by tobozo** [comment]
@per1234 as usual thanks for your lightning speed feedback :superhero: 

I'll use the arduino lint action as per your suggestion, the lack of notification makes perfect sense now :+1:
